### ISSUE TITLE
[PE-D][Tester E] Parsing of Improper Values

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-2/tp#143]
Able to input negative values for servings when logging food

![image.png](https://raw.githubusercontent.com/sweijie24/ped/main/files/918981ee-0e4d-47a9-adcd-27ee39dd522b.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sweijie24/ped#3

**Comment by alvinnnnnnnnnn** [comment]
someone done already
