### ISSUE TITLE
[PE-D][Tester A] Error handling for invalid whole number Height and Weight inputs not present

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W12-2/tp#151]
![image.png](https://raw.githubusercontent.com/AhmedShaiyan/ped/main/files/b5476fd7-c0ae-4bf2-bfad-0cfd89a4cdb1.png)

No exception handling present for such invalid input. Perhaps include a suitable range for height and weight  (eg. 60 < height in cm < 250)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: AhmedShaiyan/ped#2

**Comment by alvinnnnnnnnnn** [comment]
fixed !!!!
