### ISSUE TITLE
[PE-D][Tester E] Parsing of Negative Inputs for Logging

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-2/tp#152]
Able to input negative duration and calories when logging exercise.

![image.png](https://raw.githubusercontent.com/sweijie24/ped/main/files/8d8c738c-2d2f-4ad9-9db0-a9391d8ab865.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: sweijie24/ped#8

**Comment by alvinnnnnnnnnn** [comment]
someone done already
