### ISSUE TITLE
[PE-D][Tester E] Missing Summary Feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-W12-2/tp#159]
Showing summary throws an exception despite it being a function in the UG.

![image.png](https://raw.githubusercontent.com/sweijie24/ped/main/files/ce95f37f-e813-4f96-aaa8-9f5f89740601.png)

As per UG:

![image.png](https://raw.githubusercontent.com/sweijie24/ped/main/files/1c1e73aa-1166-4044-af8e-f15ae8c75b87.png)

-------------
Labels: `severity.High` `type.DocumentationBug`
original: sweijie24/ped#11

**Comment by alvinnnnnnnnnn** [comment]
Pradeep done all
