### ISSUE TITLE
[PE-D][Tester B] Functional bug - "Show" function 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-2/tp#169]
![image.png](https://raw.githubusercontent.com/HikoHikoHiko/ped/main/files/d1a65e7e-d29e-49a8-84ad-dfc659fef9f9.png)

"show food" and "show exercise" are not implemented properly. Upon adding in food data and exercise data, the output correctly as described in UG.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: HikoHikoHiko/ped#5

**Comment by alvinnnnnnnnnn** [comment]
edit UG and DG

**Comment by alvinnnnnnnnnn** [comment]
should be FoodData and ExerciseData
