### ISSUE TITLE
[PE-D][Tester D] the show g function ignores what comes after g resulting in weird interactions

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-2/tp#177]
![image.png](https://raw.githubusercontent.com/dtaywd/ped/main/files/8fa15c36-adb9-4ea5-a692-226ff937bd92.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: dtaywd/ped#14

**Comment by alvinnnnnnnnnn** [comment]
doneee
