### ISSUE TITLE
[PE-D][Tester D] recorded date should just be a date

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-2/tp#183]
![image.png](https://raw.githubusercontent.com/dtaywd/ped/main/files/0f984cdf-477f-43a1-8ba6-ae57b5c7f1ba.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dtaywd/ped#17

**Comment by SuveenE** [comment]
Since users can add the same meal multiple times during a day, we wanted to record the HH:MM also.
