### ISSUE TITLE
[PE-D][Tester A] BMI calculator suggestion

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-W12-2/tp#207]
### Suggestion

The BMI calculator currently does not do much for you overall program. Perhaps use it to give users a recommended calorie intake?

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: AhmedShaiyan/ped#10

**Comment by alvinnnnnnnnnn** [comment]
lol can't find any info on how to use it, cause calorie consumption is based on your activity level, bmi etc etc, not just BMI

**Comment by alvinnnnnnnnnn** [comment]
I feel this enhancement a bit redundant the BMI is just to show if ppl are underweight, normal, overweight or obese

**Comment by SuveenE** [comment]
We'll be displaying the BMI under summary.
