### ISSUE TITLE
Should we not display the water section when it is empty? 

### ISSUE THREAD

**Issue by SuveenE** [AY2324S2-CS2113-W12-2/tp#271]
![image](https://github.com/AY2324S2-CS2113-W12-2/tp/assets/75742713/69f96d5a-06b0-4540-85b0-8d35c696c5d1)

**Comment by SuveenE** [comment]
Also here we say logged data for today. What's the suitable wording for this?

**Comment by alvinnnnnnnnnn** [comment]
> Also here we say logged data for today. What's the suitable wording for this?

is is not suitable
