### ISSUE TITLE
invalid warning for adding exercise and food item

### ISSUE THREAD

**Issue by pradeep-cod** [AY2324S2-CS2113-W12-2/tp#274]
by putting spaces before and after the slashes, the command still should work
must make sure if put spaces after c/ and s/ and d/ the command still should work
![buggg](https://github.com/AY2324S2-CS2113-W12-2/tp/assets/110800450/b978b8ef-a246-4e43-b66e-3b0b78228e3c)

**Comment by SuveenE** [comment]
![image](https://github.com/AY2324S2-CS2113-W12-2/tp/assets/75742713/b0055b13-00ed-47dd-a5be-54bf7c99aa93)
@pradeep-cod can you take a pull and run this again? It works for me

**Comment by pradeep-cod** [comment]
bro tried, still not working, 

can you try input "add e / laughing c/ 10 d / 10"

may be if got space before the slash may have error?

**Comment by pradeep-cod** [comment]
![Screenshot (260)](https://github.com/AY2324S2-CS2113-W12-2/tp/assets/110800450/acb50fa5-2e00-41a5-a850-d4843750894e)
